import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Button, buttonVariants } from '@/components/ui/button'
import Link from 'next/link'






const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

//making the sideMenu
function SideMenu() {
  return (
    <div className="pb-12 w-1/4">
      <div className="space-y-4 py-4">
        <div className="px-3 py-2">
          <h2 className="mb-2 px-4 text-lg font-semibold tracking-tight">
            Discover
          </h2>
          <div className="space-y-1">
            <Button asChild
             variant="secondary" className=" w-full justify-start flex gap-3 rounded-2xl hover:bg-slate-800 ">
              <Link href='/gallery'>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" className="w-6 fill-yellow-500 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 15.75l5.159-5.159a2.25 2.25 0 013.182 0l5.159 5.159m-1.5-1.5l1.409-1.409a2.25 2.25 0 013.182 0l2.909 2.909m-18 3.75h16.5a1.5 1.5 0 001.5-1.5V6a1.5 1.5 0 00-1.5-1.5H3.75A1.5 1.5 0 002.25 6v12a1.5 1.5 0 001.5 1.5zm10.5-11.25h.008v.008h-.008V8.25zm.375 0a.375.375 0 11-.75 0 .375.375 0 01.75 0z" />
              </svg>

              Gallery
              </Link>
            </Button>
            <Button asChild
            
             variant="ghost" className="w-full justify-start flex gap-3 rounded-2xl hover:bg-slate-800 ">
              <Link href="/album" >
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" className="w-6 fill-zinc-600 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M2.25 12.75V12A2.25 2.25 0 014.5 9.75h15A2.25 2.25 0 0121.75 12v.75m-8.69-6.44l-2.12-2.12a1.5 1.5 0 00-1.061-.44H4.5A2.25 2.25 0 002.25 6v12a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18V9a2.25 2.25 0 00-2.25-2.25h-5.379a1.5 1.5 0 01-1.06-.44z" />
              </svg>

              Albums
              </Link>
            </Button>
           
            <Button asChild
            variant="ghost" className="w-full justify-start flex gap-3 rounded-2xl hover:bg-slate-800  ">
              <Link href='/favorites'>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" className="w-6 fill-rose-600 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
              </svg>
               
                Favorites
                </Link>

               
            </Button>
            
            
          </div>
        </div>
      </div>
    </div>
  )
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="text-gray-50  bg-zinc-950">
      <body className={inter.className}>

        <div className="border-b ">
          <div className="flex hover:shadow-gray-400  hover:shadow-md h-16 text-2xl font-bold  items-center px-8 container  mx-auto">
            <div className='flex gap-2'>
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" className="w-8 fill-gray-600 h-8">
                <path stroke-linecap="round" stroke-linejoin="round" d="M6.827 6.175A2.31 2.31 0 015.186 7.23c-.38.054-.757.112-1.134.175C2.999 7.58 2.25 8.507 2.25 9.574V18a2.25 2.25 0 002.25 2.25h15A2.25 2.25 0 0021.75 18V9.574c0-1.067-.75-1.994-1.802-2.169a47.865 47.865 0 00-1.134-.175 2.31 2.31 0 01-1.64-1.055l-.822-1.316a2.192 2.192 0 00-1.736-1.039 48.774 48.774 0 00-5.232 0 2.192 2.192 0 00-1.736 1.039l-.821 1.316z" />
                <path stroke-linecap="round" stroke-linejoin="round" d="M16.5 12.75a4.5 4.5 0 11-9 0 4.5 4.5 0 019 0zM18.75 10.5h.008v.008h-.008V10.5z" />
              </svg>

              Photos App

            </div>


            <div className="ml-auto flex items-center space-x-4">
              <Avatar className=' rounded-full h-12 w-12'>
                <AvatarImage src="data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAoGBxMTExYRERQXFhYWGBgcFxgZGRkYGRYWGRkZGCAcGBkZICoiGR0pHxkWJDQjJysuMTExHCE2OzYwOiowMS4BCwsLDw4PGBERFjAfGB8wLi4uLjAwMC4uMDAuLjAwMDAwMC4wMDAwMC4wMDAuMDAwMDAwMDAwLi46OjAuMDAuMP/AABEIAOEA4QMBIgACEQEDEQH/xAAcAAABBAMBAAAAAAAAAAAAAAAAAwYHCAECBQT/xABKEAACAQIDBgMEBgQMBQQDAAABAgMAEQQSIQUGBxMxQSJRYTJCcYEUUpGhscEjYnJzCCUzNUNTdIKy0eHwFZKTs8IkNGOiFhdk/8QAFwEBAQEBAAAAAAAAAAAAAAAAAAECA//EABsRAQEBAAMBAQAAAAAAAAAAAAABEQIhMRJB/9oADAMBAAIRAxEAPwCUFFZhGrftf+K0LWYfe+P/AIrUUstKqKTWlVoNgK2tWora9AUUXrIoE5Yga8jp2NdCtHjB60HBxuz1cWYXrnS7MUdFH2U6zhRWDgl71nBG+09iqbgxgjytf50yN4d3Bq8Skfq9qneTCxe8wrmYxNng/pXX4E/l1oK043DOp1B0ryXvoasVtDB7InGUrc+aCx+01wMdu3seMlhg8ROfIOco/wCVgPzq6IQIt1rWpjEOyXbK2zOWen8owsPWzD7r138Du7sSRQn0SO+hJDObAENqxa/ugdddR0Jp9GK+1vHGW0AJ+AvVjv8A9Y7Jl5hjhy54yhCsbKSQ4ZQejgjqOxI6aU14+G0sOPeTKqYOCOWRbe+TEygeZYEn4Bb6Fq0iFqKzWKAooooCiiigcPDf+dMH/aI/8VWrqqvDQX2pg/36fcb1aqgib6T60UhyjRQSYKzF73x/8RWBWYu/x/IVFLJSopJaUFBms0Cs0GRW4rVa1lkCqWYhVUEknQADUknsKBSm/vFvlhcIDzZFv5XH+pPyBt3qK+IXF2SZ2gwJKQgkczo0tu/mE8hpcdethGGLxkkrFnYsT5m9MEybV45oCRBFf1N/z6/YKam1eLuNlPgfIPIAfidRUf0Uw128dvbi5jeSZz6Fq8sm3sQRbmED00rnUVUetNqTDpI3210MJvLiBZTIxHYXOgriVlTbWgdOI2jI69a8kmPxMYvzGQfG1J7K2qiMGkGa3Reg/vH8h9terGxRzsZGkubXOmVI17fH0GgPmKzjTo7q794mFwDKxW4zX7jTQfZb5/C07bC2/Di4rEjxizLfqCCD0+DD5GqxMozZYgT5N5+oHl66Wrq7H27NhnFpTe479Pn27fYPKqh077cJMTFLLJhUDweNkVfaVFVbLbqWLFgOui371GZFWL3M4gw4jLBI3isAT2LfVHe9vy7nRt8QOGEKYSXEYW5dGDgaexdiwv5eO/l4RSVEL0Vu61pVBRRRQOjhT/O2D/e/+LVaSqscLv51wf75fwNWnoIsy0UplrFTVPxazD3+P5ChazF3+JoFlrcVotbig2FI7SUmGUKSDy3sQbEHKbEEdDS4pRRQcHcreBcXh4nJ/SGNSwNvF0BYW00OhHY+hUloced4JI8OuEhveXWQj6g93TzpgxbzTbLmfD2zLDKylCSpOQlA6ONUfKBqOqmxuK923eKAlUtH42YWImhjLp29tLBh8qCNGBGh0rWvVjce8pu9vkAK8tVBRRS+Gwxc2UqPVmVB9rED5daBCilJUyki4PwII+RGhp18OdxZNpSm5ZIUF3kFr3uLKL9zr18qBoE0VY7ZvCfZ0X9BzD5yEt93T7q8+2eEOBlByRmI9ihIt8joaz9LivQNbFydCT/rUkbb4L4mO7QSLIL6Bhla3x6E/ZTD2vsefDNkxETRn1Gh+BGhqyyo80eIdRZWsD5UjRRVHe3SiYzpk89T2A66j/PT49KsZu9KJ4GhkF1y5Df3rjxX9dSfsqBeHyEv4R94B+VvF/yi/qKmfdPGBpBAg0UeLyUdcoA9knvfXz9cX1qeIE322WuFxuIwyCyo9h8Cob8+lcOnxxn2jDNtKUQjSOyOwtZ5B7R07jRbn6gHbVj1uMiiiigcvC8/xrg/3y/nVp6qduFNk2jg2/8A6YR9sij86tjQRjRWKKin6tEXf4n8aFrMff4n8aBVa3FaLW4oNhSq0ktLLQQlx63NcSf8ShW8bhRMB1R1GUN+yyhR6Ff1qiGrG8ZMIsuFA5pikW7IQdHt1Rgex873HrqKrrISSb9aqNKKKKAr14GOIkmZ2VQOirmZj5C9gPia8lFBsx1NqlLgdthoJHQgmJ7AnsH6jXu3XQjNppcXtFdOXdBcTLIseHhebL7o0UX8yfCB0PiuNOl9alFoYpAdR3pQ1x9gQypCizG72F9b2PkCdSB6k11onvWYtJkj2WHXp61xd4d34MQpilRWBHcV0MaxQhmH6Puy3BQ9iQOq+vat5XyqHJDAe0R9Qn2tPLqfgalioXx3CJBMQsrLEwIuRcxsfZP6yg9R1tfW9R1tfZEuGxEmGnGV4myt3FvrDzUggj0IqzeOyguD7pt01N9R8etqi7jZgMjYbG5QxjdoJr9HCgSRhvO6NIpPpV42/qVzOHewxJK2HmdwtldXhc5ZI2OUMtvbGbw2YXBNiLjw9PeniGmBEmC2bEVYrY4lnDNlI0MYAsOoN/u6GsjDJgMLPjUvLEUjGHu2VhHiSlzm88qrcD3lJ7k1Hr4nDSMzTc5DfTIqOCOugLrkv1tdrVpHJkYk3JuTqSepPrWlenFtGTaJSqi9sxux9WI0+Q6evWvNVBRRRQOLhthOZtPCLppPG2v6jBrfHSrVVVLh21tp4L+0w/e4FWtoItvRWMtFRUgpWY+/xP41hazH+Z/E0Cq0oKTWlVoNlpQUmtKCgh7+EfLIq4YD+TfPf0dbd/UN0/V7d4Vqw/H7ZZm2bzV64eVXP7Dfoz97KfgDVeKqCivdsjBc17akKLkD2m1ChV8iWZVv2vftTpl3HlkQ5cLLh5NBGWbmQzPlLcvMQDHIV9m5KsbL4SRcGRRSkiFSVYEEaEEWIPqKToHVwy3aTH41IZrmNQWcAkEqO1x62GmutWP2VsqHDoI4YljQdFUAD7upqEv4Pf8A76Sw/oGJNuniUdfn/oeqz2grF9WMSZVF20FMfePiaIDIuHwOJxHKJEj5GjiUjr4ipY288oHrXT3y2jAoKYiR4QRlLcwJG6ki6sL3W/TMQvUDN1pjDiIkEy4PZ0MbwqACypJKEIvflpERzFOhGo1za1ob7sccIchXHxy5yx8UaxtGFJ8rqwABtbxE2+VSBs/ExtGcRAFOHILqwYMrx2uwC+6LX8OlmW1tagTiPtCGWZgsaxzITzT9GfClm8ihmkudb3IU6dTcVzd196JcISgZjBIRzYg1g1iCGF7gMCq9RYgWIIJFEWAxu0VhLI/hEWIWLmaHLG0XPRjfqEJym/RbtXM3v2emI2Viswu0kTYlNDmurvIvzyZFPxNcHYW9sW0WaSSIJEizO8AkEs+KnfD8iyRizCNYi5LNoC41sCR28DvzhMLChxMyyTBIkUIylZLKsZKNfKFJUyXYhQHGtwbJAwN+Z3w2yMBs6UkTsDJKp0ZIg0hjVh1B8fT9Q1GxFOviVhpBtCZ5ZObzSJEfzhkGaPT3bJlFvSmtIbnSqrWiisgfdRC7QWQO3vE5R5gaFvhfT1IPlXnrs71xZZIlHsfRsMU7XDQI7H/qNJ871xqDvcPv5ywX9ph/7i1a6qscN8OTtHCP2XEQ/PxirT0EYWora1ZqKfS1mLp8z+JrC1mLp8z+JoFVpVaTWlFoNhSgpMUoKDx7Y2euIhlw8nsyoyN8GBFx661UXEQlHZG6qxU/EGxq49VU4jbP+j7SxcXYTMw/Zk/SAfY4qo7PBiDmY1lAUssTuA3RsmoT4Fih/uU8eLe8UMSQwiSVsRmMyRoQqhmJMUkzWJJQWKxi2up0teL9ydu/QsbDifdRrP3vG4KPp38LE28wKkraGzWnxGLxkMRfETQxw4eN/AqylBGzwyyWjkUxLzIyGuQToDQcre7Y8u1l+nYOMFI40LhbWEjoJHQAd1J1+IqNsbhGikaN7ZlNjY3F/iKmnhNtR9nxPgMdFJCfpOjOuVSJI7DK3RvHHbS9+YvYGo24n4uKXamKkg9guB0y+JUVH0/bDfGgkD+DnhVCYmY2zsUUDuEFzf5n8KmKM1V/hzvY+z8TmGsctlkGpuL3BFu4P4mp22bvkkiq62IYAg9NDWL1VdvG7IikbPy0EgIIcqrHQ3sb9QRcfAnpWm1MPDKtpY0zLqmdQx06Fba29AaQbemBRdzb/favPg99MJM/LUkm9gLXufh+fx8q1qGdvzs+fEwHDxYcOOis6FVTQ2ZSzllK3IHXQkWsa5G7HCNMobE+LMpufZVWBBVlJ69wRZgdOmt5iOFVjmIuOw/zrn7e27FhmihYB5sQ4WKO4BYjqxJ9lFGpP2Ak2rPavJgN3cLnObDx+JQt8gUSKvaRV8LjuLio/wBp7nPs7aGfAYRZo5Fdm+kRpJDEWe6CG1nRlsRqeltddJVklK+Jk0HvJdgPiLX+YvXqYggHqD9hDf62q8Sq1b3bJxJkklmDPJISztbqT/sADsAKa02DkTVlIB72q120dgQyjVRXMx+42GlQLkCkd7XvU2xeqrHhsKzmwFd6PdmT6PNIBqi5viq2ZvsUE08t79wZopS0EZIBsLDQ/Cnjw13VlWAvikKs18qNroRbUeRGhHe5q/WmIMXaiPCsGIQty7iKVSBJGpJYobi0iZiWCmxBJswBIrnkLcWJI9Rb8zUh7/cJ58Mz4jCDmYcalL3khGvUH20HZhc26jQmo7dCpsRV1k7uHjAY3Cjznht/1FqzVVl3TXLNsyUe9jCvxCyYa33sas1SLUaWora1FQPdKzH+Z/E1hKzH+Z/E1QqtKrSS0oDQbitxSamtcQWCMUAZwDlUnKGa2gJsbAnvY2oPRVb+Oaj/AIo7ra0kULBh74yBc1+/s2+VOWbittDZ7mDF4cSgX5TSHlylAbDmFCysR0JHW3U9ai3bG1ZMQ/MlYmwKoCb5EzMwQE65RmIHkLDoBVR4KkjcDiNPg4VjxULYjCIwyNYZ4WBuOWW0YA9Aemmo6VG9TTwu2Gk2zuXIukjNfr30+3/fnUtweXb+8uxsQUl5s0k4cGIESry3LaNIWYqQCb6eVRpvVhTFi8RGeqyuDpb3j2qSN6eEkOHi58M0hKul0cgAguAbGwKnXqTUfb8zo+PxLxuXVpnIYgg2J6EEA6dNfKko4gNODdzackasokOgOWMAm/XQeXc29K4mHdQfEuYW6dPv+F6VhxZUswAu2h62yk6r1vY9Dr0uO9UOLDwY7FeJTcFmPX2ABoPPzAv1NPThBs0/SXu3MaMgO4N1HW6jTrcH7L+Qpi7F288eHnscrFQqkHL1sCFAHWwPTzHYC0i/weoHKTSmyxqbeVyep8z0tmPkQO9QSjtjaIgjz5WkcnLHGmryOeir5eZY6KASbAGmJvTuTjJEXaCOJNoxyLJlvaNYgGHIhvYAC98x1Y3JtcW8W9fGPDRSuuEXnMvg53VQM3iEd9CNL36MbdQBTbl4nY/GMUghkcE2yIpNr+ZXprf5VRmfi5tfDShcTDEB/VvGy3UGxysGvfQi+uvapD3b4hpi4wjwPDO+cCK4drqAMwUWcLmNrlQBYkkDWoe2/sHamJctJDnN2YhZInMd7XzqrnliwW97agnqTUncHhIJp0miEUi4bALoVYSqqzgSBkJVrjKL3PQ+VBJdFFFAUUVqWAoEplBtcXubfEEaj4f5VWniNsyODEOE9ksSvprVidq43KpCXZiCAF1tf8TUW7a3fjgY7S2rYRxG8OHHieaXqoe2iLfqO/ewFjz+t5NZkNXAwmLF7Jwh9uJsO8gtYrJPiBNlPqIzALed6sfVcdyubitow4qXxPJio5HPa/MU2HkB0A7CrHVuMo0zUVrRRo/ErMdYShKIVWtxSQNKA0CimlVpFTSiGgjDiPwijxLS4zBsUmY5misvLkYnVrkjITe5OvQ6XNRHt3dafDoZSGaHPlWTIVDAg5XseitZrHvb4Va6vFtTBwyRyJOivG4AcOLggdND69PWiKrbr7FfF4hIE6sbk2uFUakkXGlWE2FhVw6ciP2YUXyGt9elcHdowxYjEkYZMM2YKkVgGEKqMpBGjBmzNddNba5ace7sRlOIJtqth563+6s8qseLiviSuz5StiSqsAdQQGDG47iwOnfp3quUz5mLHqST3PXXqdT86sRvfgnxeyS6KWkiRsyj2mC3VwLg+IAZgO5W3eq5kVrigoooqgpw7u74T4ODEYeHpiEyEkn9GDcMUHZiDa/brrpZvUUD94P7jDaE5lnH6CGxYf1jG9l+Glz/AK1I21OECuhTD4/FQjsjNniA6WCLksLev+VMXgpvnhsDJJFiSUExW0nVQ17ePXwL6gerGwFpd2/hpsfhv/QYvlJKp/SZbgoRa6EEMD11vQQXvPwu2hgyTy+fGPfhu9h+slsy/Zb1rkbC3tx2D0w2IeMfV0ZdCT7DAjqzdu5r372xy4DaDxiXNJCxCyXOYqy3s3fVW8ybN1JFSruHudFjMABtbDtJiEkdWeXMsoGjAc0HOygN3OhuO1A3t2+O8i2THwCQf1kRCtb1jbwsfgV+FP7ZPFPZU7BFxIjY9pVaMf8AMwy/fTN3n4EKbvs+bL/8U2o+CyKLgfEH41HW8e4G0MEM+Iw7csdZEIkQD9YrfJ/etQWjilVgGUgg9CDcH4Eda1VQwue9VS3e3oxeBbPhJ3jv7S6FG/aRrqT62vUkbp8Y8TqcYkcq205YKSs1wAABdWZr6LYdOoqWaJkSADp/qfnXO3m3egxsLQTr4bGxGhQ26j8flXj3X31wuOZooSwkQXZGA6A5SVZSVYA3FwextTglYBST0AN79LetT5ki6gvcXFRxY+LCgg/plCnzs3+lTxVbdmYpG29A0PsfS0tbp4nANqslSFRty6KXtRQPBKwtZjrVTVCgrcGkwa2BoFQa2BpIGstKFBZiFVQSxJsAALkk9gBQcbf/AHnXZ2CkxGnMIyxKfela9tO4GrH0U1A26W+88WJVsVPNJC73lQyMVJJJDFTpo1m08vlW3E/fVtpYklCRh47rCuouO7sD7zW+QsPO7PqotCuy4MXGrNqtrxyqbNGTb2W8jpobg6XFbbBwsmCMq4gqyMy8uVQQLW6SD3GufMg6a30qLuCu/XIlXAYlv0UmkbN7jnopv7p6fMelpskm5Zyvqp6E63HkfX8azimvFvCuFxGIwvLLl25sQBCraRQWDsfZGYHoDofSoU312JaR8RBEyRZiJUKuggmJduWOYFLeFc1wLa2qat5tzjLJFjcC4WWHpGxIjdQcwXMviSxvYezZmGgYmmvtnZzI0mzMLnjlmi5rXQ5i5aPMpKRlFUn2pR4TlQAXzE2IhKinPvxuz9CeNeZG5aJWblMZFW9wPHlA1yn8dbmmxVBRRRQFdfZm82LgXJDM6Ja2UHS2Yvp5EMxYEag61yKKDu4PmbRxIEz2Zke7+WVWZb+maw+FO3gtvnJDjuTiJWMWK0Jc6CawCMSe5Ayet1v0FRzCxBupIOuoNtLa6/Cu7w6wQm2lhI2BI5yMQBckIc9reXh1PYXNBausVmigbe3NwtnYoES4WIMdc8aiOS/nmSxPzuKY+K4GiKRJcFiiDG6uqTpmBZSCLvHbT+7Tt3o4kYLAycmUszj2ggBy97HXrTL2xx5UXGGw1/JpDp8SBU1cODcHhzJg5/pmIkTOqMiJEWKhDf2mYLm0t7o1AOmt+Dxt3/UJ/wAPwkoLMf0zIbgJb2Mw94nrbt8aj/eLiTtHF3WScoh9yPwD5kammsxvqetB3eHf854P+0xf4xVraqnw5H8Z4L+0Rf4hVrKqGFais0VFOqOkwa3jpInWilQa2BrzzYlUUvIwVVF2ZiAqgdyToBUVb9cYLEw7M+DTsL/9JT/iPyHeiJE3o3wwmATNiZLMRdYl8Ur/ALK30HqSB61D+/nFabHRnDQR8iBj4/FmeVfJiAAq9yo+21MPFYp5XMkjs7sbszEszHzJOppGqgooooCp54Q7+rjYxs/GNedF/Rs2vORfU9ZF+8a661A1LYXEvG6yRsVdSGVhoQw1BFSzRZHbeOl2e3OszxD21AJzR9yP1h18zqNb135IcNjoFY2kjdcyOpKsuYe0jqQyNbuCKbHDjfKPamG5WIsJl8LjpnsPaXy07UhshX2TjBhHN8HiWJw7WsIpjctEx6DNqw6dwKmq4++nDeVMMkMBaTDxNLI2Rc2JZmtYOAQsqjXxZS4AACmoe2XFGXVZswW5zAWv06i/lrcelW6VqaO9fDzC4pmnREjnIN2y3SS/9Yo6n9Yaj1GhsqK5Y7CBWOW4Us2QNoxCnW/l/oR1BpbY2xZMQJ3GiYeJpJW8gNFX9pmsPtPau7tncXHQycqdStj1XxIwGmdSLZtLeRGgtTs3nxiQbNxEMUK4dEiw8BAABmxEpSWQk2u5WGNfEb+2aoT3U4XbO2jAk2Fxkoa45iOqFkHdbC1j1s+o9DSeM4DYsX5WJhcAHLmDoSb9CAGA07366etMzc/eh8FIGBYAdGT201ubAkB0JAujaHsQbmrAbmb6w41QpNpLA9CFkH1kJ9dLdQQR1BACJ8NwR2ibZmw6XU+1IzWNjoQqHXUai9rE66VJPDnhrHswmVpOdMwIzZciqptcAXJPTqfsFPmigKKKKCuXFHdd4cTIxYkMxIJ1vfWmEwsbVLnGvbCyz8uP+jGVj5sCb/5fKooxfWsxaQooorSHnwWwnM2thulk5jm/6sbWt63K1Zmq4cC5LbWgXzSb/tsfyqx9QMfLRW+Ws0U4Upo77b+YfZ91c8yYi6xKdfQueiD46+QNO5KrPxIP8Z4u/wDXN+VBnezfTFY9v0z5YwfDElxGvxHvH1N/S1N2iiqgooooCiiigKKKKDtbpbdOEnWQ5mQkCRVOViv1kPuyL1U+eh0JBn2LGRY3DjC4pw8c4H0fEp4c7WDpf+pxK6Nl6Na6+8q1opy7oS86RMM7soJAUAlQ63LctrHWzHOvcENbUipYJ93Q2xIWkwOKP/qcPYMbWE8Z9iZPRh1HYhh2pwYnEpEjSSMFRFLOx6Kqi5J9LCot2hPiYJcOcQS80Vxh8TpeeFtWw85GnM0zI/Rio6Em6/FzegjZQVG8WJdUuDa8QHMYj42RSP16zna704uC4o4nFYmZxBNLhkF1hijSTlxg25koKli2oJyuttde443E7bqYnDYaSFXWOSWZmVxY544cMi6+8AjA5r++R1F66XB3HNhBO2SMiRUVmZynQsUI8LaHOQb26C165XE/AqmFwhikjlRpcU+eIhkGZcMLEjoTYG3rW0MvY+z3xEyQxlVZzYF2yrf1NSxuluxtfZz8xJMNJE4OaPnHlknowFgFJt1Hrp2pvcMt3MHi0YS41oZQdY7R2ta2YF73Go+Y70+9lboQmWOGDFvLGtzL4U0QXsoYDr2ub9+9ssD13V2nLiIebNEIiSQoD8wMo73sP9iuuTXlSZIxktkVRZRay5RoMp6fLr6U2d5d6418KtbS/Xzpbiya7m2NuxYdSzG9hewqJdu8WZWlPLAVRoO9hXl3k3kLggHQ+tMXHG4JA61n1cwrt7bTTyNK5uzG5Pma4btc3rLjWta1IlrFbAX6Vi1KLGw6aGqh+cEdkzttOCcQycqPm8yTKQi5oZFALHS5LLp1qxdV44GY3Ef8TSPmScspKZELNlNkNiRe182XWrD0DRyUUtloqK6q1WfiOb7Sxf75vyFWXWqzcRD/ABli/wB+/wCNIVwKKKKqCiiigKKKKAooooClIZCrBlJVlIIINiCNQQexvSdAFBYrcna0G18BaUDmR2WaMaZXGodLaqGtmFvZIIHSo74j4nPjYcIvjjwykeIACSSRsz37WtkQkeyQfKmzuRvXNs6fnRHRlKOp1DKRobdypsw+FuhNS1u3ujzYlaWNZYpf0mdmuXz651I1V2ubsLdTmB6Vnwcfh2YuZLgZVJDAGPN7RXVcrD6wsyMPrKfOvZPs7BQ5MNiwFimldEc6hZHWL2z7t8lr+gPrSHEjdGfBtFtLAFmEWkoNiUXSzN9ZLDKxuLWU9iR0tm4zC7Ww8uFlAXEArIsD63kQEnlsbXDKxBFgy5iSO9UM3aO5LYLacIjw4xURVpOSxHjVbK6jMLEgMrCpA3d3teVZMNJg/wDhwaKXlujjMGRCfADGFLBVdrgm2Q3HS/M3fxhTHYGCWTmNG8qRs9uYYJIGcA31axjj8Xk4vqCakTG4KJ5o72zBXzAEeKM2BDL7wJsPtpKGTwm4mDGgYTFsBiQPC2gE6gdh0DgdR36juB2d7+HGGxrc1WeCa1s8fst5Z4z4T16ix9agHe2IYfHzLBG+GEUx5aFmzx5T4WDdRewYEE2uLE9am7hlxHXHxLDKCcWtldVAs6/12tgF+sPO1hqBVEXb5cP9o4HNI6c6Aa82K5AH66+0mnUm49TTPXE30NXBpk71cKtn4ws4j+jyn+kisoJ63ZPZOvU2BPnTDVbZetainPvJue+F5rxyLPFC/LlZVZJIWJsOdE+qBjfKwLKfPW1N94xoRQbxRgqa6OGwyuQB3A+4V5cLHoadO5Ow/pE8Sr1vr3uO9xWa1Di4I7HK7QaXXKuHe2hGrPGPwzfZU302dz93jhnkcqAWAAItqL37fKnNViU2rUUty6KK9i1WLf8A/nHF/v5P8Rqzy9KrJv4l9pYsf/PJ/iNIlcCilDEa0tVRgCi1emDDkmlJoSB0ouPFRWTRbvRGKUdAO9z6dPtpOigKAaKKANTLwD3z67Lmb6z4ck/No/xYf3vSodjUd6Ww2JaKRJYmKujBkYdVZTcEfOpe1W8ZfOo43x3EaF1xmz/BkbPIqglkAu14lAObXt7vUXAsHHuXtz6fhY8XA4UnSaJvGqyKPEoN8y30IOuhGmtdqHaIzCOQcuQ3srHR7a3RujD7+umlZzBD2KxAbbuzp1FubkNtPCWaRWUHuFfmL8AvnUi4tJZEx+KhYs5jkgw6qSADEGW/bxc4ya+QFq4PFnZCYfk7UiWz4WdJJFHRlZkUkDsbiP06+t3humpiwuFil/lWhDN38Vgz6/tPWkRfvLsk7Y2YuPVLY/CAx4hLeKTl+0CPrWs4+LLrpUW7D2tLhZ48TA2WSM3U9j2II7qRcEeRq08OylixT4mMW5ygTDszp7D/ABsWU+d1+rUGcady/oWJGIgW0GIJIA6Ry9WT0B9pR+0BotJRNW5G9Me0cMuIj0b2ZEvcxyAar6juD3BFd6qwcNd8H2ZihIbmGSyzr5pfRx+styR56jvVi5sUn6LFxMGjcKrMpuGjfVHBHUBmGvQK7ntVDJ4sRR4SbD7TyApI30bGJa4mw8ik+MDqQFax88vkKi7fbdZtnYp4vbhbxRP5xtqAT5jpfva9T9v3sEY3Az4b3mS8fpIviT/7AD4E0yH2OdrbFw0iDNPDHkIPtMYv0ZBv7xy3/vGpViHUYC4qUP4P8AkmnlP9Eigad3J9NDZfvqOtr7Amg0lRk8swtf8A3Y/Yalj+Dts9o8NiZGFi8qr17IgPTt7dCpUoooqo42WilMtFYabrVad9l/jPF/v5P8VWXSow4lbqhsUJo4dJY1LMq2DS5mU3t1a2T7q0iPt29jHESOALhEzN6DMF1+ZH212INxs7X7U8+E2500TYiSeMoksWRCbXbxXJA7W069flTuh3XZDoVYefT7qzdUysNuNEuFkiFjI3jUkWysB09e4+dM3GbFzLlA1qesBs0q12AsPnrSGP3Sw0upTI31kNr/EdD9lTKarPjdgSKelen/8AHZOWr28Ld6nTHcNIXdWEjBfeUgEn4MLW0r3ba3OSX+TCgXvl6a99a12nSvsW6czBiB2uK5WO2dLFYyKQD0Pa/cX86sVFuY6qQoXXsTrXQ2PupGIWixMUbhnV8pAYKyag38736evnSWirNFWD23wTwE0jyRPLBmuQiZTGreYUi4F7+G/wtTcxfAdkQsuKzEAf0du2umb7NftrSIhC3pVICRpUmYLhlHGQXlL+elr/AO9Psr3ybk4ZdVGnlWbyWQ3uC+9n0LGciY2hxBVDfokt7I/oLnKT5EE9KsDiYFYZXGYXBF+xBuCD1BBsQRqKgbb+50RQ8vRgNKlHhTvIcZg8kpvPhzy5b9WsPC5/aX7w1N08e7e3Y3OwM+GViS0b5M3iy6HS/VgNbX19a9u7WPEmEwsjaGSKPt0bl3IPl0b7K6hSuZgNl8uF8Ouiq7GI/VDNzV+SMcoHkg86qOqRXJ3r2DHjsNJhZNA48Ld0caqw+Bt8Rcd66cTEqCRYkAkeR8qUoKlbc2PLBI8Mq5ZYmKuPUeXmDoQe4IqVOAm8Ykil2ZiGvYExK3eNgc6Due5t6tTi4kcP2x0sc8GRZCMkuYkAqASraA3I9k97EfVpm7v8MNpwYqGYLHHy3DcwSKwA72XqwI0IsLgnpRUxbJkbKY5CS8ZysT1YDVX9cylSbaZsw7U3dyofo2M2hgeimRcTF+7xAIYKOwWRGHzFOYQtnWTQErlcA6HuCDbWxzAdNGNeXGbHD4qHFo2R4lkjfS/MhexyHXSzqjA+h86qFtp7HgnQpLGrA3Go6X628qU2ZgEgiWKNQqqLAD/fWvXRQFFFFB4ctYpfJRUV5kr1J7ArFFAutZooogooooCiiiqCiiigKKKKBg4/+UPxNeeXpRRXJtytr+wfgfwp0cIv/Zv+/k/Kiirx9SnnRRRW2RRRRQFFFFUFFFFAUUUUBRRRQJ0UUVB//9k=" />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>
            </div>



          </div>
        </div>

        <div className='flex'>
          <SideMenu />
          <div className=' px-8 pt-8 w-full'>{children}</div>
        </div>





      </body>
    </html>
  )
}
